/* =========================================================
   Dữ liệu 8 mẫu xe BMW trưng bày
   ========================================================= */

const CARS = [
  {
    id: "3-series",
    name: "BMW 3 Series",
    category: "sedan",
    categoryLabel: "Sedan",
    bodyType: "sedan",
    color: "#f3f5f8",
    colorStroke: "#0a1428",
    colorName: "Alpine White",
    tagline: "Sedan thể thao chuẩn mực của phân khúc hạng sang",
    price: 1850000000,
    priceLabel: "1,85 tỷ",
    engine: "Turbo I4 2.0L TwinPower",
    power: 255,
    torque: 400,
    accel: 5.8,
    topSpeed: 250,
    fuel: "Xăng",
    transmission: "8 cấp tự động Steptronic",
    seats: 5,
    trunk: 480,
    description:
      "BMW 3 Series là bản giao hưởng giữa cảm giác lái thể thao và sự tinh tế hằng ngày — chiếc sedan đã định hình cả một phân khúc trong hơn bốn thập kỷ. Khung gầm cân bằng 50:50, hệ thống lái chính xác và khoang lái hướng người lái mang lại trải nghiệm cầm lái đúng chất BMW ở mọi tốc độ.",
    features: [
      "Hệ thống treo thích ứng M Sport",
      "Màn hình kép BMW Curved Display 12.3\" + 14.9\"",
      "Hỗ trợ lái bán tự động Driving Assistant Professional",
      "Đèn pha Adaptive LED tự động điều hướng",
      "Cốp điện mở rảnh tay Comfort Access",
    ],
  },
  {
    id: "5-series",
    name: "BMW 5 Series",
    category: "sedan",
    categoryLabel: "Sedan",
    bodyType: "sedan",
    color: "#8992a0",
    colorStroke: "#0a1428",
    colorName: "Mineral Grey",
    tagline: "Đẳng cấp doanh nhân, chuẩn mực điều hành",
    price: 2450000000,
    priceLabel: "2,45 tỷ",
    engine: "Turbo I4 2.0L Mild-Hybrid",
    power: 292,
    torque: 400,
    accel: 5.9,
    topSpeed: 250,
    fuel: "Xăng",
    transmission: "8 cấp tự động Steptronic",
    seats: 5,
    trunk: 520,
    description:
      "Thế hệ mới của BMW 5 Series kết hợp không gian hàng ghế sau rộng rãi, cách âm vượt trội và công nghệ hỗ trợ lái tiên tiến — người bạn đồng hành lý tưởng cho những chuyến công tác dài và các cuộc gặp gỡ quan trọng. Đây là mẫu xe của những người dẫn dắt.",
    features: [
      "Ghế sau chỉnh điện, sưởi & massage",
      "Hệ thống âm thanh Harman Kardon",
      "Cách âm chủ động Active Sound Design",
      "Cửa sổ trời toàn cảnh Panorama",
      "Sạc không dây & chiếu sáng nội thất Ambient",
    ],
  },
  {
    id: "7-series",
    name: "BMW 7 Series",
    category: "sedan",
    categoryLabel: "Sedan hạng sang",
    bodyType: "sedan",
    color: "#0e1116",
    colorStroke: "#8a929c",
    colorName: "Black Sapphire",
    tagline: "Cờ đầu công nghệ & hạng sang tối thượng",
    price: 5990000000,
    priceLabel: "5,99 tỷ",
    engine: "Turbo I6 3.0L Mild-Hybrid",
    power: 380,
    torque: 520,
    accel: 5.1,
    topSpeed: 250,
    fuel: "Xăng",
    transmission: "8 cấp tự động Steptronic",
    seats: 5,
    trunk: 500,
    description:
      "BMW 7 Series là tuyên ngôn về sự hoàn hảo — nơi công nghệ tiên phong gặp gỡ thủ công tinh xảo. Màn hình giải trí BMW Theatre Screen 31 inch, ghế Executive Lounge và cabin cách âm tuyệt đối biến mỗi hành trình thành một khoang riêng tư sang trọng bậc nhất.",
    features: [
      "Màn hình BMW Theatre Screen 31\" hàng ghế sau",
      "Ghế Executive Lounge ngả 42.5 độ",
      "Hệ thống âm thanh Bowers & Wilkins Diamond",
      "Cửa đóng mở điện êm ái Soft-Close",
      "Hệ dẫn động 4 bánh xAxis thích ứng",
    ],
  },
  {
    id: "x3",
    name: "BMW X3",
    category: "suv",
    categoryLabel: "SUV",
    bodyType: "suv",
    color: "#1c4f8f",
    colorStroke: "#0a1428",
    colorName: "Phytonic Blue",
    tagline: "SUV linh hoạt cho mọi hành trình",
    price: 2150000000,
    priceLabel: "2,15 tỷ",
    engine: "Turbo I4 2.0L TwinPower",
    power: 245,
    torque: 400,
    accel: 6.5,
    topSpeed: 210,
    fuel: "Xăng",
    transmission: "8 cấp tự động Steptronic",
    seats: 5,
    trunk: 550,
    description:
      "BMW X3 mang tinh thần thể thao của dòng M vào thân hình SUV thực dụng. Khoảng sáng gầm xe lý tưởng, hệ dẫn động xDrive thông minh và khoang hành lý linh hoạt giúp X3 sẵn sàng cho cả phố thị lẫn những chuyến đi xa cuối tuần.",
    features: [
      "Hệ dẫn động 4 bánh thông minh xDrive",
      "Ghế thể thao bọc da tổng hợp Sensatec",
      "Cốp điện chỉnh theo cử chỉ chân",
      "Hệ thống camera 360 độ",
      "Giá nóc & khoang chứa đồ mở rộng",
    ],
  },
  {
    id: "x5",
    name: "BMW X5",
    category: "suv",
    categoryLabel: "SUV hạng sang",
    bodyType: "suv",
    color: "#1c69d4",
    colorStroke: "#0a1428",
    colorName: "BMW Individual Blue",
    tagline: "SUV hạng sang toàn diện",
    price: 4290000000,
    priceLabel: "4,29 tỷ",
    engine: "Turbo I6 3.0L Mild-Hybrid",
    power: 340,
    torque: 450,
    accel: 5.5,
    topSpeed: 230,
    fuel: "Xăng",
    transmission: "8 cấp tự động Steptronic",
    seats: 5,
    trunk: 650,
    description:
      "BMW X5 là chuẩn mực của phân khúc SUV hạng sang cỡ trung — vóc dáng uy nghi, khả năng vận hành linh hoạt trên mọi địa hình và không gian nội thất cao cấp. Hệ thống treo khí nén thích ứng giữ thăng bằng hoàn hảo dù chở đầy tải.",
    features: [
      "Treo khí nén thích ứng hai trục",
      "Ghế massage chức năng đa điểm",
      "Hệ thống âm thanh Harman Kardon Surround",
      "Đèn pha Laser BMW Laserlight",
      "Chế độ lái Off-Road chuyên dụng",
    ],
  },
  {
    id: "x7",
    name: "BMW X7",
    category: "suv",
    categoryLabel: "SUV 7 chỗ",
    bodyType: "suv",
    color: "#14161b",
    colorStroke: "#9aa5b1",
    colorName: "Black",
    tagline: "SUV 7 chỗ flagship, uy nghi tuyệt đối",
    price: 6490000000,
    priceLabel: "6,49 tỷ",
    engine: "Turbo I6 3.0L Mild-Hybrid",
    power: 381,
    torque: 520,
    accel: 5.2,
    topSpeed: 250,
    fuel: "Xăng",
    transmission: "8 cấp tự động Steptronic",
    seats: 7,
    trunk: 750,
    description:
      "BMW X7 là đỉnh cao của dòng SUV BMW — ba hàng ghế rộng rãi, lưới tản nhiệt Kidney Grille phát sáng đặc trưng và cabin đẳng cấp Executive. Đây là lựa chọn hàng đầu cho gia đình lớn không thỏa hiệp về sự sang trọng.",
    features: [
      "Ba hàng ghế với hàng ghế 2 kiểu Captain Chair",
      "Lưới tản nhiệt Illuminated Kidney Grille",
      "Cửa sổ trời Panorama Sky Lounge LED",
      "Hệ dẫn động xDrive thích ứng mọi địa hình",
      "Khoang hành lý linh hoạt gập điện 40:20:40",
    ],
  },
  {
    id: "m4",
    name: "BMW M4 Competition",
    category: "coupe",
    categoryLabel: "Coupe hiệu suất",
    bodyType: "coupe",
    color: "#e2231a",
    colorStroke: "#0a1428",
    colorName: "Toronto Red",
    tagline: "Coupe hiệu suất đỉnh cao mang tinh thần đường đua",
    price: 5190000000,
    priceLabel: "5,19 tỷ",
    engine: "Twin-Turbo I6 3.0L M TwinPower",
    power: 510,
    torque: 650,
    accel: 3.5,
    topSpeed: 290,
    fuel: "Xăng",
    transmission: "8 cấp M Steptronic",
    seats: 4,
    trunk: 440,
    description:
      "BMW M4 Competition là hiện thân thuần khiết của triết lý M — động cơ 6 xy-lanh thẳng hàng tăng áp kép, khung gầm được hiệu chỉnh riêng và bộ vi sai M Sport Differential mang lại độ bám đường và cảm giác lái không khoan nhượng, sẵn sàng cho cả đường phố lẫn đường đua.",
    features: [
      "Vi sai chủ động M Sport Differential",
      "Phanh gốm carbon M Carbon Ceramic",
      "Ghế đua M Carbon Bucket Seats",
      "Chế độ lái tùy biến M Drive Professional",
      "Ống xả thể thao M Sport Exhaust",
    ],
  },
  {
    id: "i4",
    name: "BMW i4 eDrive40",
    category: "electric",
    categoryLabel: "Sedan điện",
    bodyType: "sedan",
    color: "#3fb8c4",
    colorStroke: "#0a1428",
    colorName: "BMW i Blue",
    tagline: "Sedan điện, trọn vẹn cảm giác lái không giới hạn",
    price: 2890000000,
    priceLabel: "2,89 tỷ",
    engine: "Động cơ điện đồng bộ nam châm vĩnh cửu",
    power: 340,
    torque: 430,
    accel: 5.7,
    topSpeed: 190,
    fuel: "Điện — Pin 83.9 kWh",
    range: 590,
    transmission: "1 cấp truyền động trực tiếp",
    seats: 5,
    trunk: 470,
    description:
      "BMW i4 eDrive40 chứng minh rằng một chiếc xe điện vẫn có thể thuần chất BMW — cảm giác lái cân bằng, tăng tốc tức thời và tầm hoạt động tới 590km mỗi lần sạc. Lưới tản nhiệt kín đặc trưng dòng i và nội thất tối giản mang đến diện mạo hướng tới tương lai.",
    features: [
      "Tầm hoạt động tới 590km (WLTP)",
      "Sạc nhanh DC lên đến 205kW",
      "Màn hình BMW Curved Display toàn cảnh",
      "Âm thanh lái điện tử BMW IconicSounds Electric",
      "Hệ thống hỗ trợ lái Driving Assistant Professional",
    ],
  },
];

function getCarById(id) {
  return CARS.find((c) => c.id === id);
}

function formatVND(value) {
  return new Intl.NumberFormat("vi-VN").format(value) + " đ";
}
